Filter Event Log
RocketCommunicationsInc/grm-dashboard-react pull request #58
Opened 2023-07-07 18:23 UTC by Paterma

2023-07-07 22:58 UTC, Paterma commented on src/common/EventLog/EventLog.css
> +  height: 20rem;
Setting a height on the container so it doesn't shrink if there aren't many search values

2023-07-10 16:49 UTC, NicDominguez requested changes

2023-07-10 17:25 UTC, Paterma commented on src/common/EventLog/EventLog.css
> +  height: 20rem;
Here I'm setting the height of the whole log container (wraps Event log title, input, etc) which directly affects the height of the parent container (Contact Details), so it's doing what I wanted because with little-to-no results it was shrinking Contact Details. The border here and container height is actually set within this `PanelSubContainer `component that is going to be ripped out anyways, because these borders are custom css

2023-07-10 22:15 UTC, Paterma commented on src/common/EventLog/EventLog.tsx
> +        filter=''
This filter prop on `RuxLog` doesn't account for numbers or lower case values (for the lower case specifically- I would say that's something that should be updated on Astro's end). For the numbers, to me it seems like you shouldn't be able to filter through the time if they didn't include that in that in the filter logic? But I'm not sure. 
https://astro-components.netlify.app/?path=/docs/components-log--log

2023-07-10 22:38 UTC, Paterma commented on src/common/EventLog/EventLog.tsx
> +  const filter = ''.toLowerCase();
This filter prop on RuxLog doesn't account for numbers or lower case values (for the lower case specifically- I would say that's something that should be updated on Astro's end). For the numbers, to me it seems like you shouldn't be able to filter through the time if they didn't include that in that in the filter logic? But I'm not sure.
I'm having a hard time customizing the filter values. So this logic doesn't work for numbers/uppercase. Any ideas?
https://astro-components.netlify.app/?path=/docs/components-log--log

2023-07-10 22:51 UTC, NicDominguez approved these changes
Just a console log to remove. Thanks for making the log work. There is a lot of feed back we can give for it including needing to freeze the header row in addition to the filtering issue you pointed out.

2023-07-10 22:51 UTC, NicDominguez commented on src/common/EventLog/EventLog.tsx
> +              : event.message.slice(0, 62) + '...';
wow, that works though. Good job

2023-07-10 22:51 UTC, NicDominguez commented on src/components/ContactsList/ContactsTable.tsx
> +  console.log(contacts);
remove

2023-07-10 22:52 UTC, NicDominguez commented on src/common/EventLog/EventLog.tsx
> +  const filter = ''.toLowerCase();
Your deploy preview has both lowercase and uppercase letters working and checks against the message. Checking against the time value would have to be an update to the Astro component.

2023-07-10 23:07 UTC, Paterma commented on src/common/EventLog/EventLog.tsx
> +  const filter = ''.toLowerCase();
That is so weird. Yes... it's woking now. How odd!

2023-07-10 23:08 UTC, merged