Km.subpanel removal or swap
RocketCommunicationsInc/grm-dashboard-react pull request #64
Opened 2023-07-14 15:13 UTC by kiley-mitti

Renamed SubPanel to RuxChildContainer. To retain the styles I kept it as a utility component but changed the way it worked to be more RuxContainer-y

Alternately I could just go through to the child containers and add the child-container class to a RuxContainer and that would also work, but this seemed more clean. Let me know!

2023-07-14 17:20 UTC, NicDominguez approved these changes

2023-07-14 17:28 UTC, Paterma commented on src/App.css
> +  box-shadow: 0 0 0 1px inset var(--color-border-interactive-muted);
Hooray!
One small thing- this box-shadow can be removed. Based on the PDF it isn't needed (and I know design will be like ....what?), it looks like description should just be` RuxTextarea `.  Most of the default styling on RuxContainer is probably good for most of these containers :) 
<img width="1495" alt="Screenshot 2023-07-14 at 11 25 18 AM" src="https://github.com/RocketCommunicationsInc/grm-dashboard-react/assets/97068764/6de911fc-f347-4df2-ba32-4f6e24459533">

2023-07-14 17:29 UTC, Paterma requested changes
Just one little change. 
Yay for ripping out these Panels 🎉

2023-07-14 20:41 UTC, kiley-mitti commented
so actually now that I look at the mockups this actually needs more work a lot off these don't even need to be child containers. I'm not sure we need child containers at all. working on it a bit. trying to convert to draft but it won't let me. I'll see what I can accomplish Monday!

2023-07-17 16:42 UTC, kiley-mitti commented
@Paterma Looking at the wireframes, I removed a bunch of child containers and restyled some of the pages to better match. Then I realized that Frances and I were essentially working in the same areas and so I merged her CSS changes in and resolved conflicts.

There is definitely more cleanup to do.. but this PR is getting large because it's starting to touch every major container. Wondering if we can get it in and then do a bunch of smaller PRs as cleanup.

2023-07-17 16:52 UTC, Paterma approved these changes

2023-07-17 16:54 UTC, kiley-mitti commented on src/components/ContactDetails/ContactDetails.css
> +    box-shadow: 0 0 0 1px inset var(--color-border-interactive-muted);
for SURE. In fact, we may be able to rip out the child-container thing altogether and just use various grids.

2023-07-17 16:55 UTC, merged