fix misc bugs and restyle filters
RocketCommunicationsInc/grm-dashboard-react pull request #67
Opened 2023-07-14 17:05 UTC by kiley-mitti

This is a pretty small set of changes. The GSB pop up menu was falling behind a table header, the contact table on ContactTable page had a scrollbar that never actually needed to scroll (causing a double scrollbar affect), and then I took a sec to restructure the filter notifications in the same way as TTC Monitor.

2023-07-14 17:16 UTC, Paterma commented on src/components/GlobalStatusBar/GlobalStatusBar.js
> +          <RuxMenuItem>GRM Dashboard</RuxMenuItem>
I'm not actually sure if we're going to link these apps- but this is fine for now! Maybe add an onClick toast like in monitor saying the same verbiage like "This feature has not been implemented", for now?

2023-07-14 17:19 UTC, NicDominguez requested changes

2023-07-17 16:46 UTC, kiley-mitti commented on src/components/GlobalStatusBar/GlobalStatusBar.js
> +          <RuxMenuItem>GRM Dashboard</RuxMenuItem>
yeah let me make a ticket for that.

2023-07-17 17:13 UTC, NicDominguez approved these changes

2023-07-17 17:13 UTC, NicDominguez commented
> 

Sure no prob doing it in a separate PR.

2023-07-17 17:59 UTC, merged